/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TakimlarRouteImport } from './routes/takimlar'
import { Route as TakimlarIndexRouteImport } from './routes/takimlar.index'
import { Route as TakimlarSlugRouteImport } from './routes/takimlar.$slug'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TakimlarRoute = TakimlarRouteImport.update({
  id: '/takimlar',
  path: '/takimlar',
  getParentRoute: () => rootRouteImport,
} as any)
const TakimlarIndexRoute = TakimlarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TakimlarRoute,
} as any)
const TakimlarSlugRoute = TakimlarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TakimlarRoute,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/takimlar': typeof TakimlarRouteWithChildren
  '/takimlar/$slug': typeof TakimlarSlugRoute
  '/takimlar/': typeof TakimlarIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/takimlar/$slug': typeof TakimlarSlugRoute
  '/takimlar': typeof TakimlarIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/takimlar': typeof TakimlarRouteWithChildren
  '/takimlar/$slug': typeof TakimlarSlugRoute
  '/takimlar/': typeof TakimlarIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/takimlar'
    | '/takimlar/$slug'
    | '/takimlar/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/takimlar/$slug' | '/takimlar' | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/takimlar'
    | '/takimlar/$slug'
    | '/takimlar/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  TakimlarRoute: typeof TakimlarRouteWithChildren
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takimlar': {
      id: '/takimlar'
      path: '/takimlar'
      fullPath: '/takimlar'
      preLoaderRoute: typeof TakimlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takimlar/': {
      id: '/takimlar/'
      path: '/'
      fullPath: '/takimlar/'
      preLoaderRoute: typeof TakimlarIndexRouteImport
      parentRoute: typeof TakimlarRoute
    }
    '/takimlar/$slug': {
      id: '/takimlar/$slug'
      path: '/$slug'
      fullPath: '/takimlar/$slug'
      preLoaderRoute: typeof TakimlarSlugRouteImport
      parentRoute: typeof TakimlarRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TakimlarRouteChildren {
  TakimlarSlugRoute: typeof TakimlarSlugRoute
  TakimlarIndexRoute: typeof TakimlarIndexRoute
}

const TakimlarRouteChildren: TakimlarRouteChildren = {
  TakimlarSlugRoute: TakimlarSlugRoute,
  TakimlarIndexRoute: TakimlarIndexRoute,
}

const TakimlarRouteWithChildren = TakimlarRoute._addFileChildren(
  TakimlarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  TakimlarRoute: TakimlarRouteWithChildren,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
