/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TakimlarRouteImport } from './routes/takimlar'
import { Route as TakimlarIndexRouteImport } from './routes/takimlar.index'
import { Route as TakimlarSlugRouteImport } from './routes/takimlar.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TakimlarRoute = TakimlarRouteImport.update({
  id: '/takimlar',
  path: '/takimlar',
  getParentRoute: () => rootRouteImport,
} as any)
const TakimlarIndexRoute = TakimlarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TakimlarRoute,
} as any)
const TakimlarSlugRoute = TakimlarSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TakimlarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/takimlar': typeof TakimlarRouteWithChildren
  '/takimlar/$slug': typeof TakimlarSlugRoute
  '/takimlar/': typeof TakimlarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/takimlar/$slug': typeof TakimlarSlugRoute
  '/takimlar': typeof TakimlarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/takimlar': typeof TakimlarRouteWithChildren
  '/takimlar/$slug': typeof TakimlarSlugRoute
  '/takimlar/': typeof TakimlarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/takimlar' | '/takimlar/$slug' | '/takimlar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/takimlar/$slug' | '/takimlar'
  id: '__root__' | '/' | '/takimlar' | '/takimlar/$slug' | '/takimlar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TakimlarRoute: typeof TakimlarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takimlar': {
      id: '/takimlar'
      path: '/takimlar'
      fullPath: '/takimlar'
      preLoaderRoute: typeof TakimlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takimlar/': {
      id: '/takimlar/'
      path: '/'
      fullPath: '/takimlar/'
      preLoaderRoute: typeof TakimlarIndexRouteImport
      parentRoute: typeof TakimlarRoute
    }
    '/takimlar/$slug': {
      id: '/takimlar/$slug'
      path: '/$slug'
      fullPath: '/takimlar/$slug'
      preLoaderRoute: typeof TakimlarSlugRouteImport
      parentRoute: typeof TakimlarRoute
    }
  }
}

interface TakimlarRouteChildren {
  TakimlarSlugRoute: typeof TakimlarSlugRoute
  TakimlarIndexRoute: typeof TakimlarIndexRoute
}

const TakimlarRouteChildren: TakimlarRouteChildren = {
  TakimlarSlugRoute: TakimlarSlugRoute,
  TakimlarIndexRoute: TakimlarIndexRoute,
}

const TakimlarRouteWithChildren = TakimlarRoute._addFileChildren(
  TakimlarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TakimlarRoute: TakimlarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
